name: System Version Check

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:
      - name: 1. 初始系统版本检查
        run: |
          echo "===== 初始系统信息 ====="
          echo "Ubuntu 版本:"
          lsb_release -a
          echo "内核版本:"
          uname -r  # 仅输出内核版本号（如6.8.0-1029-azure）
          echo "完整内核信息:"
          uname -a  # 输出完整内核信息
          echo "======================"

      - name: 2. 启用universe仓库
        run: |
          sudo add-apt-repository universe -y
          sudo apt-get update -y

      - name: 3. 安装编译依赖
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            build-essential flex bison g++ gawk gcc-multilib g++-multilib gettext git \
            libfuse-dev libncurses5-dev libssl-dev python3 python3-pip python3-ply \
            python3-pyelftools rsync unzip zlib1g-dev file wget subversion patch \
            upx-ucl autoconf automake curl asciidoc binutils bzip2 lib32gcc-s1 \
            libc6-dev-i386 uglifyjs msmtp texinfo libreadline-dev libglib2.0-dev \
            xmlto libelf-dev libtool autopoint antlr3 gperf ccache swig coreutils

      - name: 4. 安装后系统版本检查
        run: |
          echo "===== 安装后系统信息 ====="
          echo "Ubuntu 版本:"
          lsb_release -a
          echo "内核版本:"
          uname -r  # 仅输出内核版本号（如6.8.0-1029-azure）
          echo "完整内核信息:"
          uname -a  # 输出完整内核信息
          echo "======================"
